server:
  port: 8080

spring:
  datasource:
    username: reza20
    password: myjava123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.community.dialect.OracleLegacyDialect
